@startuml
class "RuntimeCommandBasedInputFieldComponent`1"<T> {
    + Init(inputField:TMP_InputField, parser:InputParser, validator:InputValidator, callback:Action<object>) : void
    + BindToShader(binding:ShaderBinding) : void
}
class "CommandBasedInputField`1"<T> {
}
"RuntimeCommandBasedInputFieldComponent`1" --> "cbif<T>" "CommandBasedInputField`1"
@enduml
