@startuml
class "ChangeFieldCommand`1"<T> {
    + ChangeFieldCommand(field:TMP_InputField, from:T, to:T, validator:IFieldValidator<T>, callback:Action<T>)
    + Execute() : void
    + Undo() : void
    + Redo() : void
}
ICommand <|-- "ChangeFieldCommand`1"
@enduml
