using System.IO;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using UnityEngine;

public class ProjectManager : MonoBehaviour
{
    private Project openProject;
    public MenuManager menuManager;
    public Menu newProjectMenu;

    public void CreateProjectWithUI()
    {
        StringInputElement nameInput = newProjectMenu.GetMenuElementById<StringInputElement>("ProjectNameInput");
        FileInputElement fileInput = newProjectMenu.GetMenuElementById<FileInputElement>("FilePicker");
        CreateProject(nameInput.InputField.text,fileInput.FilePath);
    }

    public void CreateProject(string name, string fbxFilePath)
    {
        //Sanitize the user name input
        name = Regex.Replace(name,@"[\s]", "_");
        name = Regex.Replace(name, @"[^a-zA-Z_]+|[^\w\s]|(?<=\s)\s+|\s+(?=\s|$)", ""); //Generated by ChatGPT because I barely know how regex works

        //Make sure the projects folder exists
        if(!Directory.Exists(Application.persistentDataPath + "/projects")) Directory.CreateDirectory(Application.persistentDataPath + "/projects"); 
        
        //Check if the project itself already exists
        int i = 1;
        string processedname = name;
        while (i < 100 && Directory.Exists(Application.persistentDataPath + "/projects/" + processedname))
        {
            processedname = name + "_" + i;
            i++;
        } 
        
        //Actually create the project
        Debug.Log("Creating project: " + processedname + " with file: " + fbxFilePath);
        Project project = new Project()
        {
            name = processedname,
            projectDirectory = Application.persistentDataPath + "/projects/" + processedname,
        };
        Directory.CreateDirectory(project.projectDirectory);
        project.modelPlusAnimationsFilePath = project.projectDirectory + "/ModelAndAnimations.fbx";
        File.Copy(fbxFilePath, project.modelPlusAnimationsFilePath);
        string projectDataJson = JsonConvert.SerializeObject(project, Formatting.Indented);
        File.WriteAllText(project.projectDirectory + "/projectData.json",projectDataJson);
        Debug.Log("Project created successfully! Opening project...");
        OpenProject(project);
    }

    public void OpenProject(Project p)
    {
        openProject = p;
        menuManager.SwitchMenu(2);
    }
}
